app_1/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
]

app_2/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_3/urls.py
from django.conf.urls import url
from .views import index
from .views import add_friend, delete
#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'add_friend/$', add_friend, name='add_friend'),
	url(r'^delete/(?P<id>\w{0,50})/$', delete, name='delete')
]

app_4/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

tugas_ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_1.urls as app_1
import app_2.urls as app_2
import app_3.urls as app_3
import app_4.urls as app_4
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'update-status/', include(app_1, namespace='update-status')),
	url(r'profile/', include(app_2, namespace='app-2')),
    url(r'stats/', include(app_4, namespace='app-4')),
	url(r'add-friend/', include(app_3, namespace='add-friend')),
	url(r'^$', RedirectView.as_view(permanent=True, url='/update-status/')),
]

app_1/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	description = models.CharField(max_length=280)
	created_date = models.DateTimeField(auto_now_add=True)

app_2/models.py
from django.db import models
from datetime import date

class Profile(models.Model):
	name = models.CharField(max_length=30)
	gender = models.CharField(max_length=6)
	description = models.CharField(max_length=100)
	email = models.EmailField()

class Expertise(models.Model):
	expertise = models.CharField(max_length=255)

app_3/models.py
from django.db import models

# Create your models here.
class Friends(models.Model):
    friend = models.TextField(max_length = 30)
    url = models.URLField()
    date = models.DateTimeField(auto_now_add = True)

app_4/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from app_1.models import models as app_1
from app_2.models import models as app_2
from app_3.models import models as app_3

# Create your models here.

app_1/forms.py
from django import forms

class Status_Form(forms.Form):
	status_attrs = {
		'class': 'form-control',
	}

	description = forms.CharField(label='', required=True, max_length=280, widget=forms.TextInput(attrs=status_attrs))

app_3/forms.py
from django import forms

class Friend_form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
		'invalid': 'Isi input dengan link',
	}
	name_attrs = {
		'type' : 'text',
		'class' : 'form-control',
		'placeholder' : 'Masukkan nama teman Anda'
	}
	url_attrs = {
		'type' : 'url',
		'class' : 'form-control',
		'placeholder' : 'Masukkan URL teman Anda'
	}

	name = forms.CharField(label='Nama', required=True, widget=forms.TextInput(attrs=name_attrs))
	url = forms.URLField(label = 'URL', required = True, widget=forms.TextInput(attrs=url_attrs))

app_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}

def index(request):
	response['author'] = "Rico Putra Pradana"
	html = 'app_1/app_1.html'
	response['status'] = Status.objects.all()[::-1]
	response['status_form'] = Status_Form
	return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		status = Status.objects.create(description=response['description'])
		status.save()
		html = 'app_1/app_1.html'
		render(request,html,response)
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

app_2/views.py
from django.shortcuts import render
from datetime import date
from .models import Profile, Expertise

# Create your views here.

mhs_name = 'Lee Jong Suk'
birth_date = date(1989, 9, 14)
mhs_gender = 'Male'
mhs_expertise = ['Actor', 'Model', 'Singer']
mhs_description = 'Currently starring in While You Were Sleeping'
mhs_email = 'jongsuk0206@daum.net'


def index(request):
    profile = Profile(name=mhs_name,gender=mhs_gender, description=mhs_description, email=mhs_email)
    expertise = Expertise(expertise=mhs_expertise)
    response = {'Name': profile.name,'Birthday': birth_date,'Gender':profile.gender, 'Description':profile.description, 'Email': profile.email, 'Expert' : expertise.expertise}
    return render(request, 'app_2/app_2.html', response)

app_3/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Friends
from .forms import Friend_form
from urllib.request import urlopen
from urllib.error import URLError

# Create your views here.
friends_dict={}
def index(request):
	friend = Friends.objects.all()
	friends_dict['friend'] = friend
	html = 'app_3/add_friend.html'
	friends_dict['add_form'] = Friend_form
	return render(request, html, friends_dict)

def add_friend(request):
	form = Friend_form(request.POST or None)
	friends_dict['valid'] = True
	if (request.method == 'POST' and form.is_valid() and url_is_valid(request.POST['url'])):
		friends_dict['name'] = request.POST['name']
		friends_dict['url'] = request.POST['url']
		friend = Friends(friend=friends_dict['name'], url=friends_dict['url'])
		friend.save()
		return HttpResponseRedirect('/add-friend/')
	else:
		friends_dict['valid'] = False
		return HttpResponseRedirect('/add-friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

def delete(request, id):
    instance = Friends.objects.get(id=id)
    instance.delete()
    return HttpResponseRedirect('/add-friend/')

app_4/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
# from django.http import HttpResponseeRedirect
from app_1.models import models as app_1
from app_2.models import models as app_2
from app_3.models import models as app_3

# Create your views here.
response = {}

def index(request):
	html = 'app_4/app_4.html'
	response['author'] = "Arkha Sayoga Mayadi"
	response['name'] = "HEHE"
	response['friends'] = app_3.Friends.objects.all().count()
	response['feed'] = app_1.Status.objects.all().count()
	response['latestPostDate'] = app_1.objects.order_by('created_date')[0]
	response['latestPostDescription'] = app_1.objects.order_by('descriptopn')[0]
	return render(request, html, response)

app_2/templates/app_2/app_2.html
{% extends "app_2/layout/base.html" %}
{% block content %}

{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/app_2.css' %}">


<title>Profile</title>
<h1 class="main-title">PROFILE</h1>

<body>
  <div id='profile'>
    <p style="text-align: center"><img class="img-circle" src = 'http://pm1.narvii.com/6382/3fdd24e4849f2c59453ca8b07e93b406e308ddfa_hq.jpg' width="200" height="200"></p>
    <h3 class="name">{{ Name }}</h3>


    <table class="profile-table" align="center" width="600" cellpadding="40" cellspacing="20">

            <tr>
                <td class="subject">Birthday</td>
                <td class="value">{{ Birthday }}</td>
            </tr>
            <tr>
              <td class="subject">Gender</td>
              <td class="value">{{ Gender }}</td>
            </tr>
            <tr>
              <td class="subject">Description</td>
              <td class="value">{{ Description }}</td>
            </tr>
            <tr>
              <td class="subject">E-mail</td>
              <td class="value">{{ Email }}</td>
            </tr>

        <tr>
          <td class="subject">Expertise</td>
          <td class="value-exp">
              {% for ii in Expert %}
              <span class="badge">{{ ii }}
            </span>
          {% endfor %}
        </td>
      </tr>
    </table>
  </div>
</body>


{% endblock %}

app_2/templates/app_2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="APP 4">
	<meta name="author" content="{{author}}">

	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{static 'css/app_2.css'}">

	<title>
		{% block title %} Profile
		{% endblock %}
	</title>
</head>
<body>
	<header>
		{% include "app_2/partials/header.html" %}
	</header>
	<content>
		{% block content %}

		{% endblock %}
	</content>
	<footer>
		{% include "app_2/partials/footer.html" %}
	</footer>

</body>
</html>

app_2/templates/app_2/partials/footer.html
<p>Hati2 ini untuk tugas PPW Gasal 2017/2018. Dibuat oleh Arkha Sayoga Mayadi, Fari Qodri Ananda, Hema Mitta Kalyani, Rico Putra Pradana</p>

app_2/templates/app_2/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/update-status/">Status</a></li>
        <li><a href="/profile/">Profile</a></li>
        <li><a href="/add-friend/">Friends</a></li>
        <li><a href="/stats/">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app_3/templates/app_3/add_friend.html
{% extends "app_3/layout/base.html" %}
{% block content %}
<body style = "background-color: white">
<hr style = "clear: both;">

<style>
	a {
		text-decoration: underline;
		color: white
	}
	a:hover{
		color: orange;
	}
	#title {
		color: mediumspringgreen;
	}
	#label1 {
		padding-top: 30px; 
		padding-right: 20px; 
		color: white;
	}
	#label2 {
		width: 100%; 
		padding-top: 30px
	}
	#button{
		background-color: #00BFFF; 
		margin-bottom: 20px;
		transition: all 0.5s;
		border-radius: 50px;
	}
	#button:hover {
		font-size: 120%;
		background-color: #00BFFF;
		-webkit-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2);
		box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2);
	}
	#button:active {
	    background-color: #00BFD0;
	    box-shadow: 0 5px transparent;
	    transform: translateY(4px);
	}
	
	.alert-dismissable {
		width: 50%;
		font-size: 85%;
	}

	#add-input {
		margin-bottom: 50px;
	}

	.friends-list{
		text-align: center;
		border: 2px solid #000;
		background: background: #fff;
		height: 300px;
		position: relative;
		z-index: 15;
		margin-bottom: 50px;
		-webkit-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
		-moz-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
		-o-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
		box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);
		transition: 0.5s all;
		-webkit-transition: 0.5s all;
		-moz-transition: 0.5s all;
		-o-transition: 0.5s all;
		background-color: #00BFFF;
		overflow: auto;
	}

	.flex {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		justify-content: flex-start;
		align-items: flex-start;
		align-content: flex-start;
		margin-right: -15px;
		margin-left: -15px;
	}

	.flex-item {
		padding: 0 15px;
		flex-grow: 0;
		flex-shrink: 0;
		flex-basis: 25%;
	}

	.friends-list:hover {
		-webkit-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
		-moz-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
		-o-box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
		box-shadow: 0 12px 25px 10px rgba(0, 0, 0, 0.2);
		-webkit-transform: translate(0, -5px);
		-moz-transform: translate(0, -5px);
		-o-transform: translate(0, -5px);
		transform: translate(0, -5px);
	}

	#friend-image {
		border-radius: 100%;
		width: 110px;
		height: 110px;
		display: block;
		margin: 30px auto 20px;
	}

	.friends-list .friend-list-name {
		font-size: 24px;
		font-weight: 700;
		padding: 5px 5px 0 5px;
		color: black;
	}

	.friends-list .friend-list-url {
		padding: 10px 0 0;
		z-index: 15;
		text-align: center;
		overflow: auto;
	}

	@media only screen and (max-width: 768px) {
		.flex-item {
			padding: 0 15px;
			flex-grow: 0;
			flex-shrink: 0;
			flex-basis: 100%;
		}
	}

	@media only screen and (max-width: 1199px) {
		.flex-item {
			padding: 0 15px;
			flex-grow: 0;
			flex-shrink: 0;
			flex-basis: 50%;
		}
	}
	
	.friends-list .to-do-list-delete {
		background: red;
		color: #fff;
		padding: 10px;
		font-size: 16px;
		width: 100%;
		height: 50px;
		bottom: 1px;
		position: absolute;
		cursor: pointer;
		z-index: -1;
		-webkit-border-radius: 0 0px 2px 2px;
		-moz-border-radius: 0 0px 2px 2px;
		-o-border-radius: 0 0px 2px 2px;
		border-radius: 0 0px 2px 2px;
		-webkit-transition: all 0.3s ease;
		-moz-transition: all 0.3s ease;
		-o-transition: all 0.3s ease;
		transition: all 0.3s ease;
		border: 1px solid #000;
		margin-bottom: none;
	}
	.friends-list:hover .to-do-list-delete {
		font-size: 150%;
	}

</style>
<body>
<section name = 'add-input' style="text-align: center; background-color: #00BFFF;" id = 'add-input' class= 'button'>
	<div class = 'container'>
	<h1 style = "text-align: left"><font face = "Verdana" color = "gray"> Add Friend </font></h1>
		<form style = 'width: 100%;" id = 'form' method="POST" action="{% url 'add-friend:add_friend' %}">
			<div>
				<table>
					<tbody>
						{% csrf_token %}
						{% for i in add_form %}
						<tr>
							<td id = 'label1'> {{i.label}} </td>
							<td id = 'label2'> {{i}} </td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<br>
				<button id = 'button' type = 'submit' class = "btn pull-right btn-primary"> 
					<font color="black"> Add Friend </font> </button>
		</form>
</section>


</section>
		{% if not valid and not first %}
	<div class="alert alert-danger alert-dismissable">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<strong>Sorry!</strong> You've added an invalid friend.
	</div>
	{% endif %}

</section>

<section name="my-list" id="my-list">
    <div class="container" id = 'contain'>
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="friends-list">
                            <div class="friend-list-image">
                                <img id="friend-image" src="http://www.sbsc.in/images/dummy-profile-pic.png" alt="profile-image"/>
                            </div>
                            <div class="friend-list-name">
                                {{data.friend}}
                            </div>
                            <div class="friend-list-url">
                                <a id = "url" href="{{ data.url }}" target="_blank">{{ data.url }}</a>
                            </div>
							<div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" id="delete" data-id="{{data.id}}" onclick="delete(data-id)">Delete</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
</body>
{% endblock %}

app_3/templates/app_3/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<style>
footer {
	text-align: center;
	background-color: #cccccc;
	padding-top: 15px;
	padding-bottom: 5px;
}
</style>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="APP 3">
	<meta name="author" content="{{author}}">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

	<title>
		{% block title %} Add Friend
		{% endblock %}
	</title>
</head>
<body>
	<header>
		{% include "app_3/partials/header.html" %}
	</header>
	<content>
		{% block content %}

		{% endblock %}
	</content>
	<footer>
		{% block footer %}
		{% include "app_3/partials/footer.html" %}
		{% endblock %}
	</footer>
	
	<!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
    $(function() {
        $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
            if (target.length) {
                $('html, body').animate({
                    scrollTop: target.offset().top - 55
         }, 1000);
         return false;
       }
     }
   });
 });

        $(".to-do-list-delete-button").on("click", function(e) {
        var uid = $(this).data('id');
        location.href="delete/" + uid;
});
    </script>

</body>
</html>

app_3/templates/app_3/partials/footer.html
<p>&copy; Hati2 ini untuk tugas PPW Gasal 2017/2018. Dibuat oleh Arkha Sayoga Mayadi, Fari Qodri Ananda, Hema Mitta Kalyani, Rico Putra Pradana</p>

app_3/templates/app_3/partials/header.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/update-status/">Status</a></li>
        <li><a href="/profile/">Profile</a></li>
        <li><a href="/add-friend/">Add Friend</a></li>
        <li><a href="/stats/">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app_4/templates/app_4/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="APP 4">
	<meta name="author" content="{{author}}">

	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{static 'css/app_4.css'}">

	<title>
		{% block title %} Dashboard
		{% endblock %}
	</title>
</head>
<body>
	<header>
		{% include "app_4/partials/header.html" %}
	</header>
	<content>
		{% block content %}

		{% endblock %}
	</content>
	<footer>
		{% block footer %}
		{% include "app_4/partials/footer.html" %}
	</footer>

</body>
</html>

app_4/templates/partials/footer.html
<div class="container"><p>>Hati2 ini untuk tugas PPW Gasal 2017/2018. Dibuat oleh Arkha Sayoga Mayadi, Fari Qodri Ananda, Hema Mitta Kalyani, Rico Putra Pradana</p></div>

app_4/templates/partials/header.html
<nav class="navbar navbar-inverse bg-primary fixed-top navbar-light bg-faded">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/update-status/">Status</a></li>
        <li><a href="/profile/">Profile</a></li>
        <li><a href="/friends/">Friends</a></li>
        <li><a href="/stats/">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="APP 4">
	<meta name="author" content="{{author}}">

	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{static 'css/app_4.css'}">

	<title>
		{% block title %} Dashboard
		{% endblock %}
	</title>
</head>
<body>
	<header>
		{% include "app_4/partials/header.html" %}
	</header>
	<content>
		{% block content %}

		{% endblock %}
	</content>
	<footer>
		{% block footer %}
		{% include "app_4/partials/footer.html" %}
	</footer>

</body>
</html>>

templates/partials/footer.html
<p>Hati2 ini untuk tugas PPW Gasal 2017/2018. Dibuat oleh Arkha Sayoga Mayadi, Fari Qodri Ananda, Hema Mitta Kalyani, Rico Putra Pradana</p>

templates/partials/header.html
<nav class="navbar navbar-inverse bg-primary fixed-top navbar-light bg-faded">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/update-status/">Status</a></li>
        <li><a href="/profile/">Profile</a></li>
        <li><a href="/friends/">Friends</a></li>
        <li><a href="/stats/">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>